export const makersList = [
  "Acura",
  "Honda",
  "1ZAZ",
  "Audi",
  "BMW",
  "Bentley",
  "Alfa Romeo",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "GMC",
  "Chrysler",
  "Dodge",
  "Ram",
  "Jeep",
  "Ford",
  "Fiat",
  "Lincoln",
  "Genesis",
  "Hummer",
  "Hyundai",
  "Kia",
  "Jaguar",
  "Isuzu",
  "Land Rover",
  "Infiniti ",
  "Lexus",
  "Maserati",
  "Mazda",
  "Mercedes Benz",
  "Mitsubishi",
  "Mercury",
  "Nissan",
  "Mini ",
  "Pontiac",
  "Scion",
  "Smart",
  "Subaru",
  "Plymouth",
  "Porsche",
  "Saturn",
  "Oldsmobile",
  "Suzuki",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const typeOfIgnitionList = [
  "Keyed Turn Ignition",
  "Push To Start",
  "Slot",
  "Twist Knob",
  'Mazda 2"',
];

export const typeOfKeyList = [
  "Keyless Entry Remote",
  "Smart Key (proximity)",
  "Transponder Key",
  "Remote Flip Key",
  "Remote Head Key",
  "Keyed Turn Ignition",
  "Remote Flip Key (Proximity)",
  "Remote Flip Key (proximity)",
  "Blank Head Key",
  "Fobik Key",
  "Fobik Key (proximity)",
];
